name: Pre-Merge Actions

on: 
  pull_request:
    branches:
      - main
      - develop
      - feat/**
      - fix/**
      - refactor/**
      - chore/**
  pushes:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.18.1
      
      - name: Set Up JDK              // 1
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change wrapper permissions  // 2
        run: chmod +x ./gradlew

      - name: Run Tests                   // 3
        run: ./gradlew test

      - name: Build Project               // 4
        run: ./gradlew assemble
