name: GitHub Commit To Trello Comment

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: kagof/trello-link-github-action@v1.1.0
        with:
          board-identifier: "${{ secrets.TRELLO_BOARD_ID }}"
          trello-token: "${{ secrets.TRELLO_API_KEY }}"
          marker: 'LIVE-'
